#ifndef QIOF_STATUS_H
#define QIOF_STATUS_H
typedef enum QIOF_Status{
	QIOF_SUCCESS,
	QIOF_FAILURE,
	QIOF_THREAD_FAILURE,
	QIOF_NO_MEMORY, 
	QIOF_CANT_LOADSO,
	QIOF_BAD_PARAM,
	QIOF_OUT_OF_RANGE, 
	QIOF_INVALID_DISK, 
	QIOF_NOT_SUPPORTED, 
	QIOF_NOT_FOUND,
	QIOF_IO_ABORTED,
	QIOF_IO_ERROR, 
	QIOF_INVALID_ADDRESS, 
}QIOF_Status;
#endif
